fix and bump CI (#46)
* bump CI

- use clang-17 and gcc-14
- return cmake 3.30 for lint

* use hacks for cmake

* treat failed lint as error

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -34,6 +34,16 @@ jobs:
       with:
         apt_packages: 'sudo,wget,libx11-dev,xorg-dev,ca-certificates,gpg'
         build_dir: build
+        install_commands: | # Awful, dirty hacks to get the cmake version we need
+          (test -f /usr/share/doc/kitware-archive-keyring/copyright || \
+            wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
+            | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null) && \
+          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | \
+            sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null && \
+          sudo apt-get update && \
+          (test -f /usr/share/doc/kitware-archive-keyring/copyright || \
+            sudo rm /usr/share/keyrings/kitware-archive-keyring.gpg) && \
+          apt-get -y install kitware-archive-keyring cmake
         cmake_command: |
           cmake -Bbuild -S. -DCMAKE_EXPORT_COMPILE_COMMANDS=on -DGLFW_BUILD_WAYLAND=off
         clang_tidy_checks: '' # Use closest .clang-tidy config, not some weird default
@@ -42,3 +52,7 @@ jobs:
     # Upload review results as artifacts, a different workflow posts them
     # as comments. This is required due to security stuff.
     - uses: ZedThree/clang-tidy-review/upload@v0.21.0
+
+    # If there are any comments, fail the check
+    - if: steps.review.outputs.total_comments > 0
+      run: exit 1
